update source script copyright-check

diff --git a/debian/copyright-check b/debian/copyright-check
--- a/debian/copyright-check
+++ b/debian/copyright-check
@@ -1,5 +1,6 @@
 #!/bin/sh
-# Copyright © 2016-2017  Jonas Smedegaard <dr@jones.dk>
+# Copyright 2020  Jonas Smedegaard <dr@jones.dk>
+# Copyright 2020  Purism, SPC
 # Description: helper script to update copyright_hints
 #
 # This program is free software; you can redistribute it and/or modify
@@ -17,8 +18,58 @@
 
 set -eu
 
-make -f /usr/share/cdbs/1/rules/utils.mk pre-build || true
-make -f /usr/share/cdbs/1/rules/utils.mk clean DEB_COPYRIGHT_CHECK_STRICT=1
+SKIPFILES='meta'
 
-# unconditionally merge changes - safe to do with git-tracked package
-[ ! -f debian/copyright_newhints ] || mv -f debian/copyright_newhints debian/copyright_hints
+# omit files not copyright protected nor stating copyright or licensing
+RE_omit='.*\.(ico)'
+
+# cleanup stray hint files from a previous run
+find -type f -regextype posix-egrep -regex "^.*:($SKIPFILES)$" -delete
+
+1>&2 echo 'extract metadata from binary files ...'
+RE_meta='.*\.png'
+exiftool '-textOut!' %d%f.%e:meta -short -short -recurse -ext png .
+
+RE_SKIP="$RE_omit|$RE_meta"
+
+# TODO: automate more of this manual cleanup:
+#  * strip garbage copyright holders
+#  * optionally merge equally licensed Files sections
+#  * do "sort -k2 -k1,1 -u" on copyright holders
+#  * merge copyright years for each copyright holder
+# TODO: strip files matching glob in current (only, no later) section
+_licensecheck() {
+	GLOB=$1
+	shift
+	case "$GLOB" in
+		'*') 1>&2 echo "check default section(s) ...";;
+		'') 1>&2 echo "check remaining upstream section(s) ...";;
+		*) 1>&2 echo "check section(s) $GLOB ...";;
+	esac
+	licensecheck --copyright --deb-machine --recursive --lines 0 "$@" -- * \
+		| GLOB=$GLOB SKIPFILES=$SKIPFILES perl -0777 -p \
+		-e 'BEGIN { our $GLOB = join "\n ", split(" ",$ENV{GLOB}) }' \
+		-e 's/^.*?\n\nFiles: \K/$GLOB\n /s if $GLOB;' \
+		-e 's/^.*?\n\nFiles: \K.*?(?=\n\w)/$GLOB/s if $GLOB and $GLOB =~ /^[*]\//;' \
+		-e 's/^.*?\n\n//s unless $GLOB and $GLOB =~ /^[*]$/m;' \
+		-e 's/^Files:\K /\n /mg;' \
+		-e 's/^Copyright:\K /\n  /mg;' \
+		-e 's/(?:(?<=^  )|(?<=\d{4})),\K (?=\d{4})//mg;' \
+		-e 's/:(?:$ENV{SKIPFILES})$//mg;' \
+		>> debian/copyright_hints
+}
+
+rm -f debian/copyright_hints
+
+# initially, check all to know roughly what to group and in which order
+#rm -f debian/copyright_hints
+#_licensecheck '' --check '.*' --ignore "^($RE_SKIP|debian/.*)$"
+#exit 0
+
+# check generally
+#  * omit non-copyright-protected Debian files
+_licensecheck '*' --check '.*' --ignore "^($RE_SKIP|debian/.*)$"
+_licensecheck '*/debian' --check '^debian/' --ignore '^debian/(changelog|copyright(_hints)?|source/lintian-overrides)$'
+
+# cleanup hint files
+find -type f -regextype posix-egrep -regex "^.*:($SKIPFILES)$" -delete
